apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-helloworld
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: app1-helloworld.zulu.azlog.in
    http:
      paths:
      - backend:
          service:
            name: app1-helloworld
            port:
              number: 80
        path: /
        pathType: Exact
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-helloworld-https
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    # alt cert-manager.io/issuer: "my-issuer"
    cert-manager.io/common-name: "app1-helloworld-https.zulu.azlog.in"
    cert-manager.io/alt-names: "www.app1-helloworld-https.zulu.azlog.in"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app1-helloworld-https.zulu.azlog.in
    - www.app1-helloworld-https.zulu.azlog.in
    secretName: app1-helloworld-https-zulu-azlog-in-tls
  rules:
  - host: app1-helloworld-https.zulu.azlog.in
    http:
      paths:
      - backend:
          service:
            name: app1-helloworld
            port:
              number: 80
        path: /
        pathType: Exact
  - host: www.app1-helloworld-https.zulu.azlog.in
    http:
      paths:
      - backend:
          service:
            name: app1-helloworld
            port:
              number: 80
        path: /
        pathType: Exact
